### PR TITLE
Adding new UBI based images

### PR DESCRIPTION
**Pull request by lbroudoux**
In relation with fabric8io-images/java#56

New UBI based images require different methods for declaring user and settings permissions so I create a new template block specific to UBI.

Also faced an issue for retrieving agent-bond that is no longer available on old Maven central repo URL. As `agent-bond` repository is now in archive mode, I created a local `install` block that allows redefinition of URL.

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks for your support ! hope I can jump on a review/integration next week.

**Comment by lbroudoux** [comment]
Hi @rhuss 

Hope your are doing well in this particular weird moments.
I understand it could be difficult to focus on IT subjects but was wondering if you get a chance to have a look at this one...

Cheers,

**Comment by rhuss** [comment]
Yes, sorry for the delay. Indeed I'm not only distracted but also there's too much on my plate :|. 

But let me try to get this (and other image related PRs) in tomorrow, and doing a release afterwards.

**Comment by lbroudoux** [comment]
Thanks for the reply and no hurry @rhuss !
This was on my follow up list and just asking. For now I have replicated the image in my project and I’ll switch back later to the Fabric8 one.

Take care,

**Review by rhuss — APPROVED** [review]
Looks good to me 👍 

thanks !

**Pull request merged**
