### PR TITLE
Upgrade to alpine 3.9

### PR DESCRIPTION
**Pull request by i-wilson**
This is to upgrade the base image used in the fabric8 images to alpine 3.9

### CODE REVIEW

**Comment by i-wilson** [comment]
Fixes #38

**Review by rhuss — COMMENTED** [review]
Thanks ! But you should please update the alpine version in images.yml and run fish-pepper instead of updating the generated files manually.

I'm going to write some instructions how to do this soonish, but If you could modify the images.yml with your changes (alpine version and java versions), I can run fish-pepper then for you if this doesn't work out for you (fish-pepper installation is a bit tedious, probably better running it from a Docker image).

**Comment by i-wilson** [comment]
Okay, I just rewrote my commits. I'm having trouble getting fish-pepper installed inside of both node:alpine and node:latest environments so I'll let you handle that until you have some docs for it. 

Edit: Scratch that I found https://hub.docker.com/r/fabric8/fish-pepper/

**Comment by i-wilson** [comment]
Still having issues, I'll just let you handle it. :)

**Comment by rhuss** [comment]
yeah, np. I will make the re-gernation of the template more approachable (i.e. via Docker)

Thanks for the PR btw ;-) !

**Pull request merged**
